# This is a basic workflow to help you get started with Actions

name: Deploying

# Controls when the action will run.
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd ~/apps/backtest
            git checkout -f master          
            git pull
            rm -rf node_modules package-lock.json
            npm install
            npm run build 
            pm2 restart backtest
